export const images = {
    BTC: require('./../CoinIcons/bitcoin.png'),
    ETH: require('./../CoinIcons/ethereum.png'),
    ETC: require('./../CoinIcons/etc.png'),
    XRP: require('./../CoinIcons/ripple.png'),
    BCH: require('./../CoinIcons/bch_2x_hahroi.png'),
    LTC: require('./../CoinIcons/ltc.png'),
    DASH: require('./../CoinIcons/dash.png'),
    XEM: require('./../CoinIcons/nem.png'),
    BCC: require('./../CoinIcons/bitconnect.png'),
    XMR: require('./../CoinIcons/monero.png'),
    NEO: require('./../CoinIcons/neo.png'),
    MIOTA: require('./../CoinIcons/iota.png'),
    ADA: require('./../CoinIcons/cardano.png'),
    BTG: require('./../CoinIcons/bitcoin-gold.png'),
    XLM: require('./../CoinIcons/xlm.png'),
    ADA: require('./../CoinIcons/ada.png'),
    IOTA: require('./../CoinIcons/iota.png'),
    TRX: require('./../CoinIcons/trx.png'),
    EOS: require('./../CoinIcons/eos.png')
}
/*export const images = {
    BTC: 'https://res.cloudinary.com/da7jhtpgh/image/upload/v1508609483/bitcoin_eqld4v.png',
    ETH: 'https://res.cloudinary.com/da7jhtpgh/image/upload/v1508609485/ethereum_nw0chu.png',
    XRP: 'https://res.cloudinary.com/da7jhtpgh/image/upload/v1508609486/ripple_p0xeut.png',
    BCH: 'https://res.cloudinary.com/da7jhtpgh/image/upload/v1516327336/bch_2x_hahroi.png',
    LTC: 'https://res.cloudinary.com/da7jhtpgh/image/upload/v1512427497/ltc_fjbqjf.png',
    DASH: 'https://res.cloudinary.com/da7jhtpgh/image/upload/v1508609484/dash_oltvqi.png',
    XEM: 'https://res.cloudinary.com/da7jhtpgh/image/upload/v1508609486/nem_imprip.png',
    BCC: 'https://res.cloudinary.com/da7jhtpgh/image/upload/v1508609486/bitconnect_oj1bo5.png',
    XMR: 'https://res.cloudinary.com/da7jhtpgh/image/upload/v1508609486/monero_wzk3ur.png',
    NEO: 'https://res.cloudinary.com/da7jhtpgh/image/upload/v1508609486/neo_fvoo6c.png',
    MIOTA: 'https://res.cloudinary.com/da7jhtpgh/image/upload/v1512510148/miota_2x_xkby9u.png',
    ADA: 'https://res.cloudinary.com/da7jhtpgh/image/upload/v1513434489/cardano_unympj.png',
    BTG: 'https://res.cloudinary.com/da7jhtpgh/image/upload/v1513434542/bitcoin-gold_reytam.png',
    XLM: 'https://res.cloudinary.com/da7jhtpgh/image/upload/v1516326886/xlm_2x_jfwlwt.png',
    ADA: 'https://res.cloudinary.com/da7jhtpgh/image/upload/v1516326874/ada_2x_g4fs0c.png',
    IOTA: 'https://res.cloudinary.com/da7jhtpgh/image/upload/v1516327102/miota_2x_zsvtqc.png',
    TRX: 'https://res.cloudinary.com/da7jhtpgh/image/upload/v1516326885/trx_2x_ukhxjm.png'
}*/